#!/usr/bin/env python
import sys
import humanfriendly

if len(sys.argv) < 3:
  std.stderr.print("Usage duration start-timestamp end-timestamp (timestamps in seconds since the epoch)\n")
  sys.exit(1)

start = int(sys.argv[1])
end = int(sys.argv[2])
res = humanfriendly.format_timespan(end - start)
print(res)
